# Generated by Django 5.2.5 on 2025-09-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_time',
        ),
    ]
